# Définir cette configuration Compose afin de lancer l'application
# The Computer Club's Blog en production.

version: '3.9'

services:
  blog_db:
    image: "postgres:16"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "blog"
      POSTGRES_USER: "blog"
      POSTGRES_PASSWORD: "blog"
  blog_rust:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - blog_db
    command: sh -c "while ! nc blog_db 5432; do sleep 2; done && diesel migration run && ./blog"