# Définir cette configuration Compose afin de lancer l'application
# The Computer Club's Blog en production.

version: '3.9'

services:
  blog_rust:
    build: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      blog_db :
        condition: service_healthy
    restart: always
    command: sh -c "diesel migration run && ./blog"

  blog_db:
    image: "postgres:16-alpine"
    env_file:
      - .env
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      timeout: 15s
      interval: 5s
      retries: 3