# Définir cette configuration Compose afin de lancer l'application
# The Computer Club's Blog en production.

version: '3.9'

services:
  blog_rust:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      blog_db :
        condition: service_healthy
    restart: always
    command: diesel migration run && ./blog"

  blog_db:
    image: "postgres:16"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "blog"
      POSTGRES_USER: "blog"
      POSTGRES_PASSWORD: "blog"
      PGUSER: "blog"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U blog -d blog"]
      timeout: 15s
      interval: 5s
      retries: 3
      start_period: 15s