# Définir cette configuration Compose afin de lancer l'application
# Make Me Watch en production.

version: '3'

services:
  server:
    build: ./server
    container_name: serverMakeMeWatch

  client:
    build: ./client
    container_name: clientMakeMeWatch

  nginx:
    image: nginx:latest
    container_name: nginxMakeMeWatch
    ports:
      - 80:80
    volumes:
      - ./client/nginx.conf:/etc/nginx/conf.d/default.conf